# Generated by Django 5.2.17 on 2026-09-06 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='키 해시')),
                ('name', models.CharField(max_length=50, verbose_name='용도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발급일')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': 'API 토큰',
                'verbose_name_plural': 'API 토큰',
                'ordering': ['-created_at'],
            },
        ),
    ]
