# Generated by Django 5.2.17 on 2026-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='decided_via',
            field=models.CharField(blank=True, choices=[('owner', '사람(점주)'), ('rule', '규칙')], default='', max_length=20, verbose_name='확정 주체'),
        ),
    ]
