# Generated by Django 5.2.17 on 2026-09-07 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_backfill_paid_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'cancelled']), ('paid_at__isnull', False), _connector='OR'), name='order_paid_has_paid_at'),
        ),
    ]
