# Generated by Django 5.2.17 on 2026-09-06 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=32, unique=True, verbose_name='호출 ID')),
                ('tool', models.CharField(max_length=100, verbose_name='도구')),
                ('via', models.CharField(choices=[('mcp', 'MCP 도구면'), ('api', 'HTTP API'), ('admin', 'admin'), ('shell', 'shell')], max_length=20, verbose_name='경로')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='인자')),
                ('kind', models.CharField(blank=True, default='', max_length=20, verbose_name='판정')),
                ('outcome', models.CharField(blank=True, default='', max_length=20, verbose_name='결과')),
                ('rule_ids', models.JSONField(blank=True, default=list, verbose_name='규칙 ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='사유')),
                ('error', models.CharField(blank=True, choices=[('forbidden', '권한 없음'), ('denied', '세계가 거부'), ('busy', '잠금 실패'), ('exception', '예외')], default='', max_length=20, verbose_name='오류 갈래')),
                ('started_at', models.DateTimeField(verbose_name='시작 시각')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='소요(ms)')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to=settings.AUTH_USER_MODEL, verbose_name='자리')),
            ],
            options={
                'verbose_name': '도구 호출',
                'verbose_name_plural': '도구 호출',
                'ordering': ['-started_at'],
            },
        ),
    ]
