# Generated by Django 5.2.17 on 2026-09-07 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='기록 시각')),
                ('door', models.CharField(blank=True, choices=[('mcp', 'MCP 도구면'), ('api', 'HTTP API'), ('console', '콘솔'), ('admin', 'admin'), ('customer', '고객의 문'), ('shell', 'shell')], default='', max_length=20, verbose_name='문')),
                ('call_id', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='호출 ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=50, verbose_name='자리 이름')),
                ('subject_id', models.PositiveIntegerField(verbose_name='대상 ID')),
                ('subject_label', models.CharField(blank=True, default='', max_length=100, verbose_name='대상')),
                ('transition', models.CharField(choices=[('order.placed', '주문 접수'), ('order.paid', '결제 완료'), ('order.cancelled', '주문 취소'), ('stock.deducted', '재고 차감'), ('refund.proposed', '환불 제안'), ('refund.approved', '환불 승인'), ('refund.rejected', '환불 거부'), ('payment_link.issued', '결제 링크 발급')], max_length=50, verbose_name='전이')),
                ('kind', models.CharField(choices=[('ALLOW', '허용'), ('ESCALATE', '격상')], max_length=20, verbose_name='판정')),
                ('rule_ids', models.JSONField(blank=True, default=list, verbose_name='규칙 ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='사유')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='이전')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='이후')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_events', to=settings.AUTH_USER_MODEL, verbose_name='자리')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='대상 종류')),
            ],
            options={
                'verbose_name': '장부',
                'verbose_name_plural': '장부',
                'ordering': ['at', 'id'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='ledger_even_subject_e5e404_idx')],
            },
        ),
    ]
