# Generated by Django 5.2.17 on 2026-09-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='슬러그')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('emoji', models.CharField(default='📦', max_length=10, verbose_name='대표 이모지')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격 (원)')),
                ('stock', models.PositiveIntegerField(verbose_name='재고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['-created_at'],
            },
        ),
    ]
