# Generated by Django 5.2.17 on 2026-09-05 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('paid', '결제 완료'), ('shipping', '배송 중'), ('completed', '배송 완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('recipient_name', models.CharField(max_length=50, verbose_name='받는 사람')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('total_amount', models.PositiveIntegerField(verbose_name='총 결제 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('unit_price', models.PositiveIntegerField(verbose_name='단가')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='환불 금액')),
                ('reason', models.CharField(max_length=200, verbose_name='사유')),
                ('status', models.CharField(choices=[('proposed', '제안됨'), ('approved', '승인'), ('rejected', '거부')], default='approved', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='결정일')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_refunds', to=settings.AUTH_USER_MODEL, verbose_name='결정자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='주문')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '환불',
                'verbose_name_plural': '환불',
                'ordering': ['-created_at'],
            },
        ),
    ]
