# Generated by Django 5.2.17 on 2026-09-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('proposed', '제안됨'), ('approved', '승인'), ('rejected', '거부')], default='proposed', max_length=20, verbose_name='상태'),
        ),
    ]
