# Generated by Django 5.2.17 on 2026-09-06 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_refund_decided_via'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='멱등키'),
        ),
        migrations.AddField(
            model_name='refund',
            name='verdict',
            field=models.JSONField(blank=True, default=dict, verbose_name='판정'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['proposed', 'approved'])), fields=('order',), name='refund_one_live_per_order'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('order', 'idempotency_key'), name='refund_idempotency_key_per_order'),
        ),
    ]
